### ISSUE TITLE
I think I broke Minecraft

### ISSUE THREAD

**Issue by Zexpess** [MineActivity/MineActivity-Issues#14]
This is not a bug I intend for you to fix, as I'm quite certain this it is Minecraft itself which is broken. And I thought I would make you aware of it. (Not that it has any impact on the server at all)
Basically I found a bug which enables us to create stacks larger than 64. (And yes, it is magical)
First of all I found a glitch which creates minus stacks. 
![-stacks](https://cloud.githubusercontent.com/assets/10946492/6321782/e202303a-bb05-11e4-80b1-c11264131c47.png)
And yes, they too can contain more than 64 in each stack.
I did this by setting a redstone clock to a dispenser, and place fireworks in it. While the fireworks is launching, I hold right click and distribute a stack of fireworks. I'm uncertain why and how it happens, but when the stack is fully distributed and there's just one last fireworks, I middle click and somehow I end up with the opposite amount of the stack I middle clicked, like if I middle clicked a 24 stack I would get -40. THOUGH it happens incredibly rarely. I haven't found a way where it works 100%, this is the only way to my knowledge it's possible to obtain them. (I'm completely uncertain about this, don't quote me on any of this)
And now to the +64 stacks
![2015-02-23_02 37 01](https://cloud.githubusercontent.com/assets/10946492/6326489/821525fe-bb52-11e4-85d5-fd26a1f11fad.png)
Even though they may appear to be normal 64 stacks, they show their real quantity when picked up. They are fairly unstable, and can easily break into multiple stacks. I obtained them by combining the minus stacks and when for some reason when they reached more than 100'ish (I don't really know how much. It's possible that it's only 64) they turned into a 102 stack.
This bug is fairly unstable and I sometimes can't get it to work at all, but
I still think it was worthy of sharing c:

**Comment by divad** [comment]
Not our problem :palm_tree:

**Comment by Zexpess** [comment]
:C
