### ISSUE TITLE
Fix bonemeal for crops/wheat/etc.

### ISSUE THREAD

**Issue by divad** [MineActivity/MineActivity-Issues#16]
Mithril-Creative is blocking grass/wheat etc growth with bonemeal.

**Comment by Samaru** [comment]
Worldedit method for grown/growing crops:
         //set crops:1 , 2, 3, 4, 5, 6
          7 for fully grown

Also works with //repl

**Comment by divad** [comment]
So it would seem that Mithril-Creative blocks it via Bukkits BlockGrowEvent.

The event (BlockGrowEvent) is pretty rubbish.

To fix this bug we'd have to enable automatic (and bonemeal) growing of:
- Wheat
- Sugar Cane
- Cactus
- Watermelon
- Pumpkin

So it would /naturally/ grow as well. It wouldn't spread, all it means is that seeds would grow into wheat/pumpkins/melons and cactus and sugar would grow naturally to max height (only if water was flowing of course).

**Comment by divad** [comment]
Or we could just enable it for wheat only.

**Comment by divad** [comment]
FIXED
