### ISSUE TITLE
Message showing wrong vote command

### ISSUE THREAD

**Issue by Zexpess** [MineActivity/MineActivity-Issues#17]
![2015-02-28_02 12 03](https://cloud.githubusercontent.com/assets/10946492/6423970/6899c094-beef-11e4-9ed8-9ce7f7f33268.png)
As seen in the screenshot the shown command is wrong. This is due to the change in the vote command. It's now /votelinks, instead of /vote.
Essentially the message just needs to be updated. c:
https://i.imgur.com/xsND2e2.jpg

**Comment by Samaru** [comment]
Fixed.
