### ISSUE TITLE
Moderators or at least Moderators+ should be able to see players location.

### ISSUE THREAD

**Issue by Zexpess** [MineActivity/MineActivity-Issues#18]
So Bjornar and I thought about the idea, of giving Mod+'s if not also Mods, access to see where other offline player logged off. And potentially where online players are, without teleporting to them. That would save us a lot of time, since an unbelievable large ratio of players seem unable to right the endermen at spawn. That means they ask how to get to plot, being in spawn world makes them unable to execute /free and actually get a plot. It would just be a big help, as we wouldn't have to teleport to them to know if they are in the right world. 
For offline players, it would be nice to have that information. Currently /seen shows where players go offline, but only for ops. Maybe it would be possible to change that. Possibly not.
Bjornar and I both agreed that it would be fair for all staff to have that ability c:
So I hope you do too.
https://i.imgur.com/xsND2e2.jpg

**Comment by divad** [comment]
Cat wins me over.

**Comment by Zexpess** [comment]
Success :D

**Comment by divad** [comment]
Closed, permissions added to mod+
