### ISSUE TITLE
Iron doors and trapdoors are broken again :c

### ISSUE THREAD

**Issue by Zexpess** [MineActivity/MineActivity-Issues#19]
![2015-03-01_13 30 14](https://cloud.githubusercontent.com/assets/10946492/6430740/338504f8-c017-11e4-97e6-3ad7fbbbf630.png)
You cannot open iron doors or trapdoors anymore :c 
http://i.imgur.com/xsND2e2.jpg

**Comment by Puharesource** [comment]
This happens whenever the server restarts, since Mithril-Creative doesn't automatically load for some strange reason.

**Comment by divad** [comment]
See: #21
