### ISSUE TITLE
TAB, on survival, displays the number of players on freebuild, not survival

### ISSUE THREAD

**Issue by Zexpess** [MineActivity/MineActivity-Issues#25]
So it appears that the TAB on survival is displaying the wrong number. I'm not sure if this is done by intend or not, but it does seem a bit odd.
![2015-04-10_19 13 59](https://cloud.githubusercontent.com/assets/10946492/7093052/5d6a2b04-dfb6-11e4-9931-ebbfe71a3cd4.png)

**Comment by divad** [comment]
Fixed :) TitleManager plugin installed.
