### ISSUE TITLE
Plotme biome changing is bugged

### ISSUE THREAD

**Issue by Zexpess** [MineActivity/MineActivity-Issues#27]
When you change your plot's biome, by using the command /plot biome; it changes the whole plot including the outline. But when you then clear the plot, by using /plot clear, it changes the whole plot though not including the outline, to plains. So we end up with this small line of a different biome. (E.g, at the buildcomp area.)
![2015-04-18_15 50 13](https://cloud.githubusercontent.com/assets/10946492/7215771/9d36d4dc-e5e5-11e4-9685-14b5d0f6fb1f.png)
In this case the biome is jungle, while the rest of the plot is plains.
![2015-04-18_15 50 16](https://cloud.githubusercontent.com/assets/10946492/7215781/b68e6dc8-e5e5-11e4-9622-3741d0fc3026.png)

**Comment by Puharesource** [comment]
We don't have PlotMe anymore.
