### ISSUE TITLE
Tokens displaying wrong command for voting

### ISSUE THREAD

**Issue by Zexpess** [MineActivity/MineActivity-Issues#6]
![wrongcommand](https://cloud.githubusercontent.com/assets/10946492/6319333/2cbb3c0e-bab9-11e4-8461-db1101c19548.png)

As shown in the screenshot.
The command /vote is no longer functional and is replaced by /votelinks
I presume it's worth fixing, as it might confuse the players.

**Comment by divad** [comment]
I've fixed this now :)
