### ISSUE TITLE
Please regulate !time 

### ISSUE THREAD

**Issue by Zexpess** [MineActivity/MineActivity-Issues#8]
![2015-02-22_21 08 29](https://cloud.githubusercontent.com/assets/10946492/6320142/07319fdc-bad7-11e4-8a40-ff7c23802f4d.png)
Currently everyone is able to type !time as many times as they wish. Which obviously spams chat.
We can and do of course kick and mute (In that order) people who do it. 
But I think it might be wiser if we just regulate the usage of that command. It already displays the time every five minutes so it's debatable how utile the command really is.
But if you insist on having it, I suppose we just need some regulation to it.

**Comment by divad** [comment]
time is now disabled.
