### ISSUE TITLE
/undo and /redo are dysfunctional

### ISSUE THREAD

**Issue by Zexpess** [MineActivity/MineActivity-Issues#9]
As it stands now. /undo is completely broken. If typed the result is this
![undodysfunctional](https://cloud.githubusercontent.com/assets/10946492/6320886/f4bc8128-baea-11e4-9f75-1556271c15ec.png)
I'm aware that //undo and //redo work perfectly, but /undo and /redo being broken does create some disorder and confusion. And when I tried performed a large world edit, with the command //move (I had to fix Prox' spawn). It gave me the same message and deleted the entire selection that I had tried to move.
That may be irrelevant for this glitch, as it worked the second time I tried it.

**Comment by divad** [comment]
This isn't an MA bug - its a bug in WorldEdit.
